### ISSUE TITLE
Unicode decode error installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by thenewguy** [springload/draftjs_exporter#95]
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

```
  Downloading https://files.pythonhosted.org/packages/6d/e5/fcf88a5dab82ca619ff6824a062b46d9315ba91e64204275213a1a712125/draftjs_exporter-2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rmsz5l7l/draftjs-exporter/setup.py", line 91, in <module>
        long_description=md2pypi('README.md'),
      File "/tmp/pip-install-rmsz5l7l/draftjs-exporter/setup.py", line 59, in md2pypi
        content = io.open(filename).read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1727: ordinal not in range(128)
```

Any chance for a version update to master that doesn't run the markdown conversion  in the setup.py script?

**Comment by thenewguy** [comment]
Happens on 2.1.1 as well, was just working my way backwards until I read the error closer and checked where the error was coming from
